---

root: true

plugins:
  - functional

extends:
  - airbnb
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"

parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - webpack

rules:
  import/extensions: 0
  functional/functional-parameters: 0
  functional/no-expression-statement: 0
